name: CI/CD lab1

on:
    push:
        branches:
            - lab1

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   name: Install dependencies
                run: npm install

            -   name: Build the project
                run: npm run build --prod

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Log in to Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build and push Docker image
                run: |
                    docker build -t ${{ secrets.DOCKER_USERNAME }}/is:front-lab1-latest .
                    docker push ${{ secrets.DOCKER_USERNAME }}/is:front-lab1-latest

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            -   name: Deploy to remote server
                uses: appleboy/ssh-action@v0.1.5
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USER }}
                    password: ${{ secrets.SERVER_PASSWORD }}
                    port: ${{ secrets.SERVER_PORT }}
                    script: |
                        docker pull ${{ secrets.DOCKER_USERNAME }}/is:front-lab1-latest
                        docker stop lab1-front || true
                        docker rm lab1-front || true
                        docker run -d --name lab1-front -p 80:4200 --memory=2g --cpus=1 ${{ secrets.DOCKER_USERNAME }}/is:front-lab1-latest
